name: Build and Upload VitePress Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npm run docs:build

      - name: Extract version and date
        id: info
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(date +'%Y-%m-%d')
          # 保持原始版本号格式（包含逗号等特殊字符）
          ZIP_NAME="WGdocs-${VERSION}-${DATE}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT
          echo "✅ 生成文件名: $ZIP_NAME"

      - name: Create zip package
        run: |
          cd src/.vitepress/dist
          zip -r ../../../${{ steps.info.outputs.ZIP_NAME }} .
          cd ../../../
          # 确认文件存在且为正常文件
          if [ -f "${{ steps.info.outputs.ZIP_NAME }}" ]; then
            echo "✅ 验证成功：${{ steps.info.outputs.ZIP_NAME }} 是有效文件"
            ls -la ${{ steps.info.outputs.ZIP_NAME }}
          else
            echo "❌ 验证失败：${{ steps.info.outputs.ZIP_NAME }} 不是有效文件"
            exit 1
          fi

      - name: Test WebDAV file upload with curl
        run: |
          # 使用curl手动尝试上传，验证是否支持带特殊字符的文件名
          echo "📤 尝试用curl手动上传测试..."
          curl -u ${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }} \
            -T ${{ steps.info.outputs.ZIP_NAME }} \
            "https://pan.huang1111.cn/dav/WGdocs构建文件/${{ steps.info.outputs.ZIP_NAME }}" \
            --show-error

      - name: Upload to WebDAV (保留原始文件名)
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=https://pan.huang1111.cn/dav
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/WGdocs构建文件/
          include: ${{ steps.info.outputs.ZIP_NAME }}
          flatten: true  # 强制扁平化，避免创建目录
