name: Build and Upload to LanZouCloud

on:
  push:
    branches: [ main ]  # 监听 main 分支推送

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: 检查代码
        uses: actions/checkout@v4

      - name: 安装Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: 安装依赖
        run: npm install

      - name: 构建VitePress
        run: npm run docs:build  # 假设构建命令为 docs:build，需与实际项目一致

      - name: 获取版本号和日期
        id: info
        run: |
          # 从 package.json 提取版本号
          VERSION=$(node -p "require('./package.json').version")
          # 获取当前日期（年-月-日）
          DATE=$(date +"%Y-%m-%d")
          # 组合文件名
          ZIP_NAME="${VERSION}-${DATE}.zip"
          echo "zip_name=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: 打包构建文件
        run: |
          # VitePress 构建输出目录为 src/.vitepress/dist
          zip -r ${{ steps.info.outputs.zip_name }} src/.vitepress/dist

      - name: 安装 Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: 3.8

      - name: 安装最新 lanzou-api
        run: pip install --upgrade lanzou-api  # 强制安装 2024+ 版本

      - name: 上传到蓝奏云
        run: python .github/scripts/upload_lanzou.py
        env:
          ZIP_PATH: ${{ steps.info.outputs.zip_name }}
          LANZOU_COOKIE: ${{ secrets.LANZOU_COOKIE }}
          LANZOU_FOLDER_ID: ${{ secrets.LANZOU_FOLDER_ID || '-1' }}  # -1 表示根目录