name: Build and Upload to LanZouCloud

on:
  push:
    branches: [ main, master ]  # 触发工作流的分支

jobs:
  build-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        continue-on-error: false
        id: install

      - name: Build VitePress
        run: npm run docs:build
        continue-on-error: false
        id: build
        working-directory: .

      - name: Get version and date
        id: get_info
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(date +'%Y-%m-%d')
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "DATE=$DATE" >> $GITHUB_ENV
          echo "ZIP_NAME=${VERSION}-${DATE}.zip" >> $GITHUB_ENV

      - name: Package build files
        run: |
          cd src/.vitepress/dist
          zip -r ../../../${{ env.ZIP_NAME }} .
        continue-on-error: false
        id: package

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Lanzou API
        run: pip install lanzou-api
        continue-on-error: false
        id: install_lanzou

      # 替换原有的 Upload to LanZouCloud 步骤
      - name: Upload to LanZouCloud
        env:
          LANZOU_COOKIE: ${{ secrets.LANZOU_COOKIE }}
          LANZOU_FOLDER_ID: ${{ secrets.LANZOU_FOLDER_ID }}
          ZIP_NAME: ${{ env.ZIP_NAME }}
        run: |
          python - <<END
          import os
          from lanzou.api import LanZouCloud

          # 解析cookie字符串为字典
          cookie_str = os.environ['LANZOU_COOKIE']
          cookie_dict = {}
          for item in cookie_str.split(';'):
              item = item.strip()
              if '=' in item:
                  key, value = item.split('=', 1)
                  cookie_dict[key] = value

          # 检查必要的Cookie字段
          required_fields = ['ylogin', 'phpdisk_info']
          missing_fields = [f for f in required_fields if f not in cookie_dict]
          if missing_fields:
              print(f"错误：Cookie缺少必要字段：{missing_fields}")
              exit(1)

          # 初始化蓝奏云客户端并登录
          lzy = LanZouCloud()
          login_result = lzy.login_by_cookie(cookie_dict)
          if login_result != LanZouCloud.SUCCESS:
              print(f"登录失败，错误码: {login_result}")
              exit(1)

          # 上传文件
          folder_id = int(os.environ['LANZOU_FOLDER_ID'])
          zip_name = os.environ['ZIP_NAME']
          print(f"开始上传文件: {zip_name} 到文件夹ID: {folder_id}")

          # 关键修复：根据API版本调整返回值处理
          file_id = lzy.upload_file(zip_name, folder_id)
          if file_id <= 0:  # 失败时返回负数错误码，成功时返回正整数文件ID
              print(f"上传失败，错误码: {file_id}")
              exit(1)

          print(f"上传成功，文件ID: {file_id}")
          exit(0)
          END
        id: upload

      - name: Error reporting
        if: ${{ failure() }}
        run: |
          echo "工作流执行失败"
          echo "失败步骤: ${{ github.job }} - ${{ steps.install.outcome }} ${{ steps.build.outcome }} ${{ steps.package.outcome }} ${{ steps.install_lanzou.outcome }} ${{ steps.upload.outcome }}"
          exit 1