name: 构建并上传VitePress文档

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 配置Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: 安装依赖
        run: npm ci

      - name: 构建文档
        run: npm run docs:build

      - name: 提取版本和日期
        id: info
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(date +'%Y-%m-%d')
          ZIP_NAME="WGdocs-${VERSION}-${DATE}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT

      - name: 压缩文件
        run: |
          cd src/.vitepress/dist
          zip -r ../../../${{ steps.info.outputs.ZIP_NAME }} .
          cd ../../../
          echo "文件大小: $(du -h ${{ steps.info.outputs.ZIP_NAME }})"

      - name: 模拟手动上传（关键优化）
        run: |
          echo "📤 开始模拟手动上传环境..."
          # 1. 先获取手动上传时的Cookie（如果手动上传需要登录态）
          # 注意：以下Cookie仅为示例，需要替换为你手动上传时浏览器的真实Cookie
          # 如何获取：手动上传时打开浏览器F12→Network→找到上传请求→复制Request Headers中的Cookie
          COOKIE="your_manual_upload_cookie_here"  # 替换为你的真实Cookie

          # 2. 完全模拟手动上传的请求头（从浏览器复制）
          curl -v \  # 显示详细请求日志，方便对比
            -u ${{ secrets.WEBDAV_USERNAME }}:${{ secrets.WEBDAV_PASSWORD }} \
            -T ${{ steps.info.outputs.ZIP_NAME }} \
            "https://pan.huang1111.cn/dav/${{ steps.info.outputs.ZIP_NAME }}" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" \
            -H "Accept: */*" \
            -H "Accept-Language: zh-CN,zh;q=0.9" \
            -H "Connection: keep-alive" \
            -H "Content-Type: application/zip" \
            -H "Cookie: $COOKIE" \  # 携带手动上传时的Cookie
            --http1.1 \  # 强制使用HTTP/1.1（很多手动上传工具默认用这个版本）
            --show-error --fail

      - name: 若以上失败，尝试无认证信息但带Cookie上传（特殊情况）
        if: failure()
        run: |
          echo "📤 尝试仅用Cookie上传（部分服务器依赖Cookie而非账号密码）..."
          COOKIE="your_manual_upload_cookie_here"  # 同上，替换为真实Cookie
          curl -v \
            -T ${{ steps.info.outputs.ZIP_NAME }} \
            "https://pan.huang1111.cn/dav/${{ steps.info.outputs.ZIP_NAME }}" \
            -H "User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36" \
            -H "Cookie: $COOKIE" \
            -H "Content-Type: application/zip" \
            --http1.1 \
            --show-error --fail
