name: Build and Upload VitePress Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npm run docs:build

      - name: Extract version and date
        id: info
        run: |
          RAW_VERSION=$(node -p "require('./package.json').version")
          CLEAN_VERSION=$(echo "$RAW_VERSION" | sed 's/,/_/g')
          DATE=$(date +'%Y-%m-%d')
          ZIP_NAME="WGdocs-${CLEAN_VERSION}-${DATE}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT
          echo "✅ 生成文件名: $ZIP_NAME"

      - name: Create zip package
        run: |
          cd src/.vitepress/dist
          zip -r ../../../${{ steps.info.outputs.ZIP_NAME }} .
          cd ../../..
          if [ -f "${{ steps.info.outputs.ZIP_NAME }}" ]; then
            SIZE=$(du -h "${{ steps.info.outputs.ZIP_NAME }}" | cut -f1)
            echo "✅ 打包成功: ${{ steps.info.outputs.ZIP_NAME }} ($SIZE)"
          else
            echo "❌ 打包失败，文件不存在"
            exit 1
          fi

      # 方案1：修改后的上传方式
      - name: Upload to WebDAV (修正)
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=https://pan.huang1111.cn/dav
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
          include: ${{ steps.info.outputs.ZIP_NAME }}
          destination: /uploads/
          flatten: true

      # 方案3备选：cURL手动上传
      - name: [备选] Upload with cURL
        if: ${{ failure() }}  # 只有前一步失败时才运行
        run: |
          echo "尝试使用cURL手动上传..."
          curl -v -T "$ZIP" -u "$USER:$PASS" "https://pan.huang1111.cn/dav/$ZIP_NAME"
        env:
          USER: ${{ secrets.WEBDAV_USERNAME }}
          PASS: ${{ secrets.WEBDAV_PASSWORD }}
          ZIP: ${{ steps.info.outputs.ZIP_NAME }}
          ZIP_NAME: ${{ steps.info.outputs.ZIP_NAME }}