name: Build and Deploy VitePress Docs

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        continue-on-error: false

      - name: Build docs
        run: npm run docs:build
        continue-on-error: false

      - name: Check build directory exists
        run: |
          if [ -d "src/.vitepress/dist" ]; then
            echo "Build directory exists"
            ls -la src/.vitepress/dist
          else
            echo "Error: Build directory not found!"
            exit 1
          fi

      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Package build files
        run: |
          cd src/.vitepress/dist
          zip -r ../../../WGdocs-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip .
          cd ../../../
          echo "Created zip file:"
          ls -la WGdocs-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip

      - name: Upload to WebDAV
        uses: guillaumebriday/webdav-action@v1.7.0
        with:
          webdav_hostname: https://pan.huang1111.cn
          webdav_username: ${{ secrets.WEBDAV_USERNAME }}
          webdav_password: ${{ secrets.WEBDAV_PASSWORD }}
          webdav_path: /dav/根目录/WGdocs构建文件
          local_path: ./WGdocs-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip
          options: '-v'  # 详细输出模式，显示上传过程和服务器响应

      - name: Verify upload
        if: success() || failure()
        run: |
          echo "Upload process completed with status: ${{ job.status }}"
          echo "If upload failed, check the WebDAV Action logs above for server response details"
