name: Build and Deploy VitePress Docs

# 监听main分支的推送事件
on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 检出代码仓库
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # 设置Node.js环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: 'npm'

      # 安装依赖
      - name: Install dependencies
        run: npm ci

      # 构建文档
      - name: Build docs
        run: npm run docs:build

      # 读取package.json中的版本号
      - name: Get version from package.json
        id: get_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      # 获取当前日期
      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      # 打包构建结果为zip文件
      - name: Package build files
        run: |
          cd src/.vitepress/dist
          zip -r ../../../WGdocs-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip .
          cd ../../../

      # 上传到WebDAV服务器
      - name: Upload to WebDAV
        uses: mikehaertl/webdav-action@v1
        with:
          url: https://pan.huang1111.cn/dav
          path: '根目录/WGdocs构建文件'
          user: ${{ secrets.WEBDAV_USERNAME }}
          password: ${{ secrets.WEBDAV_PASSWORD }}
          local: WGdocs-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip
          remote: WGdocs-${{ steps.get_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip
