name: Build and Upload VitePress Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npm run docs:build

      - name: Extract version and date
        id: info
        run: |
          VERSION=$(node -p "require('./package.json').version")
          DATE=$(date +'%Y-%m-%d')
          ZIP_NAME="WGdocs-${VERSION}-${DATE}.zip"
          echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_OUTPUT
          echo "✅ 生成文件名: $ZIP_NAME"

      - name: Create zip package
        run: |
          cd src/.vitepress/dist
          zip -r ../../../${{ steps.info.outputs.ZIP_NAME }} .
          cd ../../../
          if [ -f "${{ steps.info.outputs.ZIP_NAME }}" ]; then
            echo "✅ 打包成功，文件大小: $(du -h ${{ steps.info.outputs.ZIP_NAME }})"
          else
            echo "❌ 打包失败，文件不存在"
            exit 1
          fi

      - name: Upload to WebDAV root (指定库)
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=https://pan.huang1111.cn/dav
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/  # 明确指定根目录
          include: ${{ steps.info.outputs.ZIP_NAME }}
          flatten: true  # 强制直接上传文件，不创建任何子目录
