name: Build and Upload VitePress Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build VitePress site
        run: npm run docs:build

      - name: Extract version from package.json
        id: extract_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Get current date
        id: get_date
        run: echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Create zip package
        run: |
          cd src/.vitepress/dist
          zip -r ../../../WGdocs-${{ steps.extract_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip .

      - name: Upload to WebDAV
        uses: bxb100/action-upload@main
        with:
          provider: webdav
          provider_options: |
            endpoint=https://pan.huang1111.cn/dav
            username=${{ secrets.WEBDAV_USERNAME }}
            password=${{ secrets.WEBDAV_PASSWORD }}
            root=/WGdocs构建文件/
          include: 'WGdocs-${{ steps.extract_version.outputs.VERSION }}-${{ steps.get_date.outputs.DATE }}.zip'